'use client';

import './globals.css';
import { Geist } from '@/lib/Geist';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';
import { WagmiProvider } from 'wagmi';
import { config } from '@/wagmi/config';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ConnectorSheet from '@/components/ConnectorSheet';
import { Toaster } from '@/components/ui/sonner';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={Geist.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <WagmiProvider config={config}>
            <QueryClientProvider client={queryClient}>
              <div className="w-full flex flex-col min-h-[740px] h-screen">
                <Header />
                {children}
                <ConnectorSheet />
                <Toaster
                  position="top-center"
                  toastOptions={{
                    style: {
                      background: 'white',
                      color: 'black',
                      border: 'none',
                    },
                  }}
                />
              </div>
            </QueryClientProvider>
          </WagmiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
